### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by Kracks** [dkovar/analyzeMFT#30]
Python 3.4.3 Installed

I run the install and receive the following ....

c:\<Directory>\IS\installers\analyzeMFT\analyzeMFT-master>python setup.py install
running install
running build
running build_py
creating build
creating build\lib
creating build\lib\analyzemft
copying analyzemft\bitparse.py -> build\lib\analyzemft
copying analyzemft\mft.py -> build\lib\analyzemft
copying analyzemft\mftsession.py -> build\lib\analyzemft
copying analyzemft\mftutils.py -> build\lib\analyzemft
copying analyzemft\__init__.py -> build\lib\analyzemft
running build_scripts
creating build\scripts-3.4
copying and adjusting analyzeMFT.py -> build\scripts-3.4
running install_lib
creating C:\Python34\Lib\site-packages\analyzemft
copying build\lib\analyzemft\bitparse.py -> C:\Python34\Lib\site-packages\analyz
emft
copying build\lib\analyzemft\mft.py -> C:\Python34\Lib\site-packages\analyzemft
copying build\lib\analyzemft\mftsession.py -> C:\Python34\Lib\site-packages\anal
yzemft
copying build\lib\analyzemft\mftutils.py -> C:\Python34\Lib\site-packages\analyz
emft
copying build\lib\analyzemft\__init__.py -> C:\Python34\Lib\site-packages\analyz
emft
byte-compiling C:\Python34\Lib\site-packages\analyzemft\bitparse.py to bitparse.
cpython-34.pyc
byte-compiling C:\Python34\Lib\site-packages\analyzemft\mft.py to mft.cpython-34
.pyc
  File "C:\Python34\Lib\site-packages\analyzemft\mft.py", line 52
    print '-->Record number: %d\n\tMagic: %s Attribute offset: %d Flags: %s Size
:%d' % (record_number, record['magic'],

   ^
SyntaxError: invalid syntax

byte-compiling C:\Python34\Lib\site-packages\analyzemft\mftsession.py to mftsess
ion.cpython-34.pyc
  File "C:\Python34\Lib\site-packages\analyzemft\mftsession.py", line 100
    print "-f <filename> required."
                                  ^
SyntaxError: Missing parentheses in call to 'print'

byte-compiling C:\Python34\Lib\site-packages\analyzemft\mftutils.py to mftutils.
cpython-34.pyc
  File "C:\Python34\Lib\site-packages\analyzemft\mftutils.py", line 52
    print "%s%s%s" % ( sep.join( "%02x" % ord(c) for c in line ),
                 ^
SyntaxError: invalid syntax

byte-compiling C:\Python34\Lib\site-packages\analyzemft\__init__.py to __init__.
cpython-34.pyc
running install_scripts
copying build\scripts-3.4\analyzeMFT.py -> C:\Python34\Scripts
running install_egg_info
Writing C:\Python34\Lib\site-packages\analyzeMFT-2.0.15-py3.4.egg-info

**Comment by vapter** [comment]
I had this issue. Fixed it by using Python 2.7 instead of Python 3.4.

**Comment by dkovar** [comment]
Vapter is spot on - analyzeMFT was never ported to Python 3.x.
